/**
 * Nifty 100 universe (Nifty 50 + Next 50 constituents) with sectors, used by
 * the pre-market scanner. Static list — constituents change a couple of times a
 * year; refresh occasionally. Sectors follow Yahoo's GICS-style buckets.
 */

module.exports = [
  // ── Nifty 50 ──────────────────────────────────────────────────────────────
  { ticker: 'RELIANCE.NS',   sector: 'Energy' },
  { ticker: 'HDFCBANK.NS',   sector: 'Financial Services' },
  { ticker: 'ICICIBANK.NS',  sector: 'Financial Services' },
  { ticker: 'INFY.NS',       sector: 'Technology' },
  { ticker: 'TCS.NS',        sector: 'Technology' },
  { ticker: 'BHARTIARTL.NS', sector: 'Communication' },
  { ticker: 'LT.NS',         sector: 'Industrials' },
  { ticker: 'ITC.NS',        sector: 'FMCG' },
  { ticker: 'SBIN.NS',       sector: 'Financial Services' },
  { ticker: 'AXISBANK.NS',   sector: 'Financial Services' },
  { ticker: 'KOTAKBANK.NS',  sector: 'Financial Services' },
  { ticker: 'HINDUNILVR.NS', sector: 'FMCG' },
  { ticker: 'BAJFINANCE.NS', sector: 'Financial Services' },
  { ticker: 'MARUTI.NS',     sector: 'Auto' },
  { ticker: 'M&M.NS',        sector: 'Auto' },
  { ticker: 'HCLTECH.NS',    sector: 'Technology' },
  { ticker: 'SUNPHARMA.NS',  sector: 'Healthcare' },
  { ticker: 'TITAN.NS',      sector: 'Consumer Cyclical' },
  { ticker: 'ULTRACEMCO.NS', sector: 'Basic Materials' },
  { ticker: 'NTPC.NS',       sector: 'Utilities' },
  { ticker: 'POWERGRID.NS',  sector: 'Utilities' },
  { ticker: 'TATAMOTORS.NS', sector: 'Auto' },
  { ticker: 'TATASTEEL.NS',  sector: 'Basic Materials' },
  { ticker: 'JSWSTEEL.NS',   sector: 'Basic Materials' },
  { ticker: 'ASIANPAINT.NS', sector: 'Basic Materials' },
  { ticker: 'BAJAJFINSV.NS', sector: 'Financial Services' },
  { ticker: 'ADANIENT.NS',   sector: 'Industrials' },
  { ticker: 'ADANIPORTS.NS', sector: 'Industrials' },
  { ticker: 'WIPRO.NS',      sector: 'Technology' },
  { ticker: 'TECHM.NS',      sector: 'Technology' },
  { ticker: 'NESTLEIND.NS',  sector: 'FMCG' },
  { ticker: 'ONGC.NS',       sector: 'Energy' },
  { ticker: 'COALINDIA.NS',  sector: 'Energy' },
  { ticker: 'HINDALCO.NS',   sector: 'Basic Materials' },
  { ticker: 'DRREDDY.NS',    sector: 'Healthcare' },
  { ticker: 'CIPLA.NS',      sector: 'Healthcare' },
  { ticker: 'APOLLOHOSP.NS', sector: 'Healthcare' },
  { ticker: 'DIVISLAB.NS',   sector: 'Healthcare' },
  { ticker: 'BAJAJ-AUTO.NS', sector: 'Auto' },
  { ticker: 'EICHERMOT.NS',  sector: 'Auto' },
  { ticker: 'HEROMOTOCO.NS', sector: 'Auto' },
  { ticker: 'GRASIM.NS',     sector: 'Basic Materials' },
  { ticker: 'BRITANNIA.NS',  sector: 'FMCG' },
  { ticker: 'TATACONSUM.NS', sector: 'FMCG' },
  { ticker: 'INDUSINDBK.NS', sector: 'Financial Services' },
  { ticker: 'SBILIFE.NS',    sector: 'Financial Services' },
  { ticker: 'HDFCLIFE.NS',   sector: 'Financial Services' },
  { ticker: 'BPCL.NS',       sector: 'Energy' },
  { ticker: 'SHRIRAMFIN.NS', sector: 'Financial Services' },
  { ticker: 'BEL.NS',        sector: 'Industrials' },

  // ── Nifty Next 50 ─────────────────────────────────────────────────────────
  { ticker: 'HAL.NS',        sector: 'Industrials' },
  { ticker: 'DLF.NS',        sector: 'Real Estate' },
  { ticker: 'VBL.NS',        sector: 'FMCG' },
  { ticker: 'SIEMENS.NS',    sector: 'Industrials' },
  { ticker: 'PIDILITIND.NS', sector: 'Basic Materials' },
  { ticker: 'IOC.NS',        sector: 'Energy' },
  { ticker: 'AMBUJACEM.NS',  sector: 'Basic Materials' },
  { ticker: 'GAIL.NS',       sector: 'Energy' },
  { ticker: 'GODREJCP.NS',   sector: 'FMCG' },
  { ticker: 'DABUR.NS',      sector: 'FMCG' },
  { ticker: 'HAVELLS.NS',    sector: 'Consumer Cyclical' },
  { ticker: 'ADANIPOWER.NS', sector: 'Utilities' },
  { ticker: 'ADANIGREEN.NS', sector: 'Utilities' },
  { ticker: 'TATAPOWER.NS',  sector: 'Utilities' },
  { ticker: 'JINDALSTEL.NS', sector: 'Basic Materials' },
  { ticker: 'VEDL.NS',       sector: 'Basic Materials' },
  { ticker: 'BANKBARODA.NS', sector: 'Financial Services' },
  { ticker: 'PNB.NS',        sector: 'Financial Services' },
  { ticker: 'CANBK.NS',      sector: 'Financial Services' },
  { ticker: 'UNIONBANK.NS',  sector: 'Financial Services' },
  { ticker: 'IDBI.NS',       sector: 'Financial Services' },
  { ticker: 'CHOLAFIN.NS',   sector: 'Financial Services' },
  { ticker: 'BAJAJHLDNG.NS', sector: 'Financial Services' },
  { ticker: 'MUTHOOTFIN.NS', sector: 'Financial Services' },
  { ticker: 'RECLTD.NS',     sector: 'Financial Services' },
  { ticker: 'PFC.NS',        sector: 'Financial Services' },
  { ticker: 'IRFC.NS',       sector: 'Financial Services' },
  { ticker: 'LICI.NS',       sector: 'Financial Services' },
  { ticker: 'ICICIGI.NS',    sector: 'Financial Services' },
  { ticker: 'ICICIPRULI.NS', sector: 'Financial Services' },
  { ticker: 'ABB.NS',        sector: 'Industrials' },
  { ticker: 'CGPOWER.NS',    sector: 'Industrials' },
  { ticker: 'RVNL.NS',       sector: 'Industrials' },
  { ticker: 'IRCTC.NS',      sector: 'Consumer Cyclical' },
  { ticker: 'ZOMATO.NS',     sector: 'Consumer Cyclical' },
  { ticker: 'NAUKRI.NS',     sector: 'Technology' },
  { ticker: 'LTIM.NS',       sector: 'Technology' },
  { ticker: 'ZYDUSLIFE.NS',  sector: 'Healthcare' },
  { ticker: 'TORNTPHARM.NS', sector: 'Healthcare' },
  { ticker: 'LUPIN.NS',      sector: 'Healthcare' },
  { ticker: 'AUROPHARMA.NS', sector: 'Healthcare' },
  { ticker: 'MANKIND.NS',    sector: 'Healthcare' },
  { ticker: 'MAXHEALTH.NS',  sector: 'Healthcare' },
  { ticker: 'SHREECEM.NS',   sector: 'Basic Materials' },
  { ticker: 'SRF.NS',        sector: 'Basic Materials' },
  { ticker: 'TVSMOTOR.NS',   sector: 'Auto' },
  { ticker: 'MOTHERSON.NS',  sector: 'Auto' },
  { ticker: 'BOSCHLTD.NS',   sector: 'Auto' },
  { ticker: 'INDIGO.NS',     sector: 'Industrials' },
  { ticker: 'UNITDSPR.NS',   sector: 'FMCG' },
];
